export type SupportDiagnosticsExport = {
  exportId: string;
  fileName: string;
  sizeBytes: number;
  appLogLineCount: number;
  debugLogLineCount: number;
  taskLogLineCount: number;
  auditEventCount: number;
  debugLogStatus: string;
  taskLogStatus: string;
  auditLogStatus: string;
  logStorageStatus: string;
  taskLogWriteFailureCount: number;
  taskLogRetentionFailureCount: number;
  auditWriteFailureCount: number;
  auditWriteFailureAfterCommitCount: number;
  auditLogRetentionFailureCount: number;
  debugLogEventRejectedCount: number;
  debugLogWriteFailureCount: number;
  debugLogRetentionFailureCount: number;
  logStorageFailureCount: number;
  logStorageUnsatisfiedCount: number;
  logStorageSettingsFailureCount: number;
};
