// Mod 库展示层数据。
// 当前文件由 scripts/generate-mod-library-mock-data.mjs 生成。
// 当前生成数量：72
// 现阶段使用本地 mock 数据还原设计稿，后续由 Mod 仓储或视图模型提供真实数据。
// 业务规则（安装、冲突、依赖判定）不在此处推断，仅承载展示字段。
import type { ModLibraryItem } from "./modLibraryTypes";
export type { ModInstallStatus, ModLibraryItem } from "./modLibraryTypes";

export const modLibraryItems: ModLibraryItem[] = [
  {
    id: "mod-001-非官方仪式礼服",
    name: "非官方仪式礼服",
    author: "NexusUser123",
    versionLabel: "v2.1.4",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#d7e7ff",
    posterTo: "#77a8ff",
  },
  {
    id: "mod-002-盛夏兔女郎套装",
    name: "盛夏兔女郎套装",
    author: "NexusUser123",
    versionLabel: "v1.0.0",
    sizeLabel: "2.9 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#eeeff3",
    posterTo: "#b5c2d6",
  },
  {
    id: "mod-003-包臀裙重制",
    name: "包臀裙重制",
    sizeLabel: "3.6 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#e0f0dc",
    posterTo: "#7cc47c",
  },
  {
    id: "mod-004-贵妇礼裙",
    name: "贵妇礼裙",
    sizeLabel: "4.3 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fbe9cb",
    posterTo: "#e8b15a",
  },
  {
    id: "mod-005-薄纱晚宴长裙",
    name: "薄纱晚宴长裙",
    sizeLabel: "5.0 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#f5e6f2",
    posterTo: "#d98bc7",
  },
  {
    id: "mod-006-夜宴礼装",
    name: "夜宴礼装",
    sizeLabel: "5.7 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#e5e7ff",
    posterTo: "#9ca3ff",
  },
  {
    id: "mod-007-雪狐披肩",
    name: "雪狐披肩",
    sizeLabel: "1.6 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#eef2ff",
    posterTo: "#a5b4fc",
  },
  {
    id: "mod-008-礼宾接待套装",
    name: "礼宾接待套装",
    sizeLabel: "2.3 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#e2f7ec",
    posterTo: "#86efac",
  },
  {
    id: "mod-009-月白礼服",
    name: "月白礼服",
    sizeLabel: "3.0 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#fff1de",
    posterTo: "#fdba74",
  },
  {
    id: "mod-010-祭典洋装",
    name: "祭典洋装",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fce7f3",
    posterTo: "#f9a8d4",
  },
  {
    id: "mod-011-月辰剑纹重涂",
    name: "月辰剑纹重涂",
    sizeLabel: "4.4 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#ede9fe",
    posterTo: "#a78bfa",
  },
  {
    id: "mod-012-公会纹章武器翻新",
    name: "公会纹章武器翻新",
    sizeLabel: "5.1 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#dcfce7",
    posterTo: "#4ade80",
  },
  {
    id: "mod-013-金狮子语音替换",
    name: "金狮子语音替换",
    sizeLabel: "5.8 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#d7e7ff",
    posterTo: "#77a8ff",
  },
  {
    id: "mod-014-猎人据点灯光增强",
    name: "猎人据点灯光增强",
    sizeLabel: "1.7 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#eeeff3",
    posterTo: "#b5c2d6",
  },
  {
    id: "mod-015-霜刃太刀外观包",
    name: "霜刃太刀外观包",
    sizeLabel: "2.4 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#e0f0dc",
    posterTo: "#7cc47c",
  },
  {
    id: "mod-016-星辉大厅换装合集",
    name: "星辉大厅换装合集",
    sizeLabel: "3.1 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fbe9cb",
    posterTo: "#e8b15a",
  },
  {
    id: "mod-017-工坊机巧锤纹理包",
    name: "工坊机巧锤纹理包",
    sizeLabel: "3.8 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#f5e6f2",
    posterTo: "#d98bc7",
  },
  {
    id: "mod-018-随从礼帽皮肤集",
    name: "随从礼帽皮肤集",
    sizeLabel: "4.5 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#e5e7ff",
    posterTo: "#9ca3ff",
  },
  {
    id: "mod-019-非官方仪式礼服-2号变体",
    name: "非官方仪式礼服 2号变体",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#eef2ff",
    posterTo: "#a5b4fc",
  },
  {
    id: "mod-020-盛夏兔女郎套装-2号变体",
    name: "盛夏兔女郎套装 2号变体",
    sizeLabel: "5.9 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#e2f7ec",
    posterTo: "#86efac",
  },
  {
    id: "mod-021-包臀裙重制-2号变体",
    name: "包臀裙重制 2号变体",
    sizeLabel: "1.8 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#fff1de",
    posterTo: "#fdba74",
  },
  {
    id: "mod-022-贵妇礼裙-2号变体",
    name: "贵妇礼裙 2号变体",
    sizeLabel: "2.5 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fce7f3",
    posterTo: "#f9a8d4",
  },
  {
    id: "mod-023-薄纱晚宴长裙-2号变体",
    name: "薄纱晚宴长裙 2号变体",
    sizeLabel: "3.2 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#ede9fe",
    posterTo: "#a78bfa",
  },
  {
    id: "mod-024-夜宴礼装-2号变体",
    name: "夜宴礼装 2号变体",
    sizeLabel: "3.9 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#dcfce7",
    posterTo: "#4ade80",
  },
  {
    id: "mod-025-雪狐披肩-2号变体",
    name: "雪狐披肩 2号变体",
    sizeLabel: "4.6 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#d7e7ff",
    posterTo: "#77a8ff",
  },
  {
    id: "mod-026-礼宾接待套装-2号变体",
    name: "礼宾接待套装 2号变体",
    sizeLabel: "5.3 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#eeeff3",
    posterTo: "#b5c2d6",
  },
  {
    id: "mod-027-月白礼服-2号变体",
    name: "月白礼服 2号变体",
    sizeLabel: "6.0 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#e0f0dc",
    posterTo: "#7cc47c",
  },
  {
    id: "mod-028-祭典洋装-2号变体",
    name: "祭典洋装 2号变体",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fbe9cb",
    posterTo: "#e8b15a",
  },
  {
    id: "mod-029-月辰剑纹重涂-2号变体",
    name: "月辰剑纹重涂 2号变体",
    sizeLabel: "2.6 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#f5e6f2",
    posterTo: "#d98bc7",
  },
  {
    id: "mod-030-公会纹章武器翻新-2号变体",
    name: "公会纹章武器翻新 2号变体",
    sizeLabel: "3.3 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#e5e7ff",
    posterTo: "#9ca3ff",
  },
  {
    id: "mod-031-金狮子语音替换-2号变体",
    name: "金狮子语音替换 2号变体",
    sizeLabel: "4.0 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#eef2ff",
    posterTo: "#a5b4fc",
  },
  {
    id: "mod-032-猎人据点灯光增强-2号变体",
    name: "猎人据点灯光增强 2号变体",
    sizeLabel: "4.7 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#e2f7ec",
    posterTo: "#86efac",
  },
  {
    id: "mod-033-霜刃太刀外观包-2号变体",
    name: "霜刃太刀外观包 2号变体",
    sizeLabel: "5.4 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#fff1de",
    posterTo: "#fdba74",
  },
  {
    id: "mod-034-星辉大厅换装合集-2号变体",
    name: "星辉大厅换装合集 2号变体",
    sizeLabel: "6.1 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fce7f3",
    posterTo: "#f9a8d4",
  },
  {
    id: "mod-035-工坊机巧锤纹理包-2号变体",
    name: "工坊机巧锤纹理包 2号变体",
    sizeLabel: "2.0 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#ede9fe",
    posterTo: "#a78bfa",
  },
  {
    id: "mod-036-随从礼帽皮肤集-2号变体",
    name: "随从礼帽皮肤集 2号变体",
    sizeLabel: "2.7 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#dcfce7",
    posterTo: "#4ade80",
  },
  {
    id: "mod-037-非官方仪式礼服-3号变体",
    name: "非官方仪式礼服 3号变体",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#d7e7ff",
    posterTo: "#77a8ff",
  },
  {
    id: "mod-038-盛夏兔女郎套装-3号变体",
    name: "盛夏兔女郎套装 3号变体",
    sizeLabel: "4.1 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#eeeff3",
    posterTo: "#b5c2d6",
  },
  {
    id: "mod-039-包臀裙重制-3号变体",
    name: "包臀裙重制 3号变体",
    sizeLabel: "4.8 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#e0f0dc",
    posterTo: "#7cc47c",
  },
  {
    id: "mod-040-贵妇礼裙-3号变体",
    name: "贵妇礼裙 3号变体",
    sizeLabel: "5.5 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fbe9cb",
    posterTo: "#e8b15a",
  },
  {
    id: "mod-041-薄纱晚宴长裙-3号变体",
    name: "薄纱晚宴长裙 3号变体",
    sizeLabel: "6.2 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#f5e6f2",
    posterTo: "#d98bc7",
  },
  {
    id: "mod-042-夜宴礼装-3号变体",
    name: "夜宴礼装 3号变体",
    sizeLabel: "2.1 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#e5e7ff",
    posterTo: "#9ca3ff",
  },
  {
    id: "mod-043-雪狐披肩-3号变体",
    name: "雪狐披肩 3号变体",
    sizeLabel: "2.8 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#eef2ff",
    posterTo: "#a5b4fc",
  },
  {
    id: "mod-044-礼宾接待套装-3号变体",
    name: "礼宾接待套装 3号变体",
    sizeLabel: "3.5 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#e2f7ec",
    posterTo: "#86efac",
  },
  {
    id: "mod-045-月白礼服-3号变体",
    name: "月白礼服 3号变体",
    sizeLabel: "4.2 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#fff1de",
    posterTo: "#fdba74",
  },
  {
    id: "mod-046-祭典洋装-3号变体",
    name: "祭典洋装 3号变体",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fce7f3",
    posterTo: "#f9a8d4",
  },
  {
    id: "mod-047-月辰剑纹重涂-3号变体",
    name: "月辰剑纹重涂 3号变体",
    sizeLabel: "5.6 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#ede9fe",
    posterTo: "#a78bfa",
  },
  {
    id: "mod-048-公会纹章武器翻新-3号变体",
    name: "公会纹章武器翻新 3号变体",
    sizeLabel: "1.5 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#dcfce7",
    posterTo: "#4ade80",
  },
  {
    id: "mod-049-金狮子语音替换-3号变体",
    name: "金狮子语音替换 3号变体",
    sizeLabel: "2.2 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#d7e7ff",
    posterTo: "#77a8ff",
  },
  {
    id: "mod-050-猎人据点灯光增强-3号变体",
    name: "猎人据点灯光增强 3号变体",
    sizeLabel: "2.9 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#eeeff3",
    posterTo: "#b5c2d6",
  },
  {
    id: "mod-051-霜刃太刀外观包-3号变体",
    name: "霜刃太刀外观包 3号变体",
    sizeLabel: "3.6 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#e0f0dc",
    posterTo: "#7cc47c",
  },
  {
    id: "mod-052-星辉大厅换装合集-3号变体",
    name: "星辉大厅换装合集 3号变体",
    sizeLabel: "4.3 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fbe9cb",
    posterTo: "#e8b15a",
  },
  {
    id: "mod-053-工坊机巧锤纹理包-3号变体",
    name: "工坊机巧锤纹理包 3号变体",
    sizeLabel: "5.0 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#f5e6f2",
    posterTo: "#d98bc7",
  },
  {
    id: "mod-054-随从礼帽皮肤集-3号变体",
    name: "随从礼帽皮肤集 3号变体",
    sizeLabel: "5.7 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#e5e7ff",
    posterTo: "#9ca3ff",
  },
  {
    id: "mod-055-非官方仪式礼服-4号变体",
    name: "非官方仪式礼服 4号变体",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#eef2ff",
    posterTo: "#a5b4fc",
  },
  {
    id: "mod-056-盛夏兔女郎套装-4号变体",
    name: "盛夏兔女郎套装 4号变体",
    sizeLabel: "2.3 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#e2f7ec",
    posterTo: "#86efac",
  },
  {
    id: "mod-057-包臀裙重制-4号变体",
    name: "包臀裙重制 4号变体",
    sizeLabel: "3.0 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#fff1de",
    posterTo: "#fdba74",
  },
  {
    id: "mod-058-贵妇礼裙-4号变体",
    name: "贵妇礼裙 4号变体",
    sizeLabel: "3.7 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fce7f3",
    posterTo: "#f9a8d4",
  },
  {
    id: "mod-059-薄纱晚宴长裙-4号变体",
    name: "薄纱晚宴长裙 4号变体",
    sizeLabel: "4.4 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#ede9fe",
    posterTo: "#a78bfa",
  },
  {
    id: "mod-060-夜宴礼装-4号变体",
    name: "夜宴礼装 4号变体",
    sizeLabel: "5.1 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#dcfce7",
    posterTo: "#4ade80",
  },
  {
    id: "mod-061-雪狐披肩-4号变体",
    name: "雪狐披肩 4号变体",
    sizeLabel: "5.8 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#d7e7ff",
    posterTo: "#77a8ff",
  },
  {
    id: "mod-062-礼宾接待套装-4号变体",
    name: "礼宾接待套装 4号变体",
    sizeLabel: "1.7 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#eeeff3",
    posterTo: "#b5c2d6",
  },
  {
    id: "mod-063-月白礼服-4号变体",
    name: "月白礼服 4号变体",
    sizeLabel: "2.4 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#e0f0dc",
    posterTo: "#7cc47c",
  },
  {
    id: "mod-064-祭典洋装-4号变体",
    name: "祭典洋装 4号变体",
    sizeLabel: "默认封面",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fbe9cb",
    posterTo: "#e8b15a",
  },
  {
    id: "mod-065-月辰剑纹重涂-4号变体",
    name: "月辰剑纹重涂 4号变体",
    sizeLabel: "3.8 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#f5e6f2",
    posterTo: "#d98bc7",
  },
  {
    id: "mod-066-公会纹章武器翻新-4号变体",
    name: "公会纹章武器翻新 4号变体",
    sizeLabel: "4.5 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#e5e7ff",
    posterTo: "#9ca3ff",
  },
  {
    id: "mod-067-金狮子语音替换-4号变体",
    name: "金狮子语音替换 4号变体",
    sizeLabel: "5.2 MB",
    status: "installed",
    categoryLabels: ["外观"],
    posterFrom: "#eef2ff",
    posterTo: "#a5b4fc",
  },
  {
    id: "mod-068-猎人据点灯光增强-4号变体",
    name: "猎人据点灯光增强 4号变体",
    sizeLabel: "5.9 MB",
    status: "disabled",
    categoryLabels: ["武器"],
    posterFrom: "#e2f7ec",
    posterTo: "#86efac",
  },
  {
    id: "mod-069-霜刃太刀外观包-4号变体",
    name: "霜刃太刀外观包 4号变体",
    sizeLabel: "1.8 MB",
    status: "conflict",
    categoryLabels: ["语音"],
    posterFrom: "#fff1de",
    posterTo: "#fdba74",
  },
  {
    id: "mod-070-星辉大厅换装合集-4号变体",
    name: "星辉大厅换装合集 4号变体",
    sizeLabel: "2.5 MB",
    status: "installed",
    categoryLabels: ["外观", "武器"],
    posterFrom: "#fce7f3",
    posterTo: "#f9a8d4",
  },
  {
    id: "mod-071-工坊机巧锤纹理包-4号变体",
    name: "工坊机巧锤纹理包 4号变体",
    sizeLabel: "3.2 MB",
    status: "disabled",
    categoryLabels: ["外观", "语音"],
    posterFrom: "#ede9fe",
    posterTo: "#a78bfa",
  },
  {
    id: "mod-072-随从礼帽皮肤集-4号变体",
    name: "随从礼帽皮肤集 4号变体",
    sizeLabel: "3.9 MB",
    status: "conflict",
    categoryLabels: ["武器", "语音"],
    posterFrom: "#dcfce7",
    posterTo: "#4ade80",
  },
];

// 快捷操作面板的动作项。
// 仅承载展示语义，点击行为由页面层透传，不在此处实现业务。
export type CompactActionVariant = "primary" | "neutral" | "success" | "warning" | "danger" | "info";

export type CompactAction = {
  id: string;
  label: string;
  variant: CompactActionVariant;
};

export const compactActions: CompactAction[] = [
  { id: "add", label: "添加 MOD", variant: "primary" },
  { id: "select-all", label: "全选", variant: "neutral" },
  { id: "invert", label: "反选", variant: "neutral" },
  { id: "refresh", label: "刷新", variant: "neutral" },
  { id: "enable-all", label: "启用全部 MOD", variant: "success" },
  { id: "disable-all", label: "禁用全部 MOD", variant: "warning" },
  { id: "reinstall", label: "重装选中 MOD", variant: "info" },
  { id: "uninstall", label: "卸载选中 MOD", variant: "danger" },
];

export const libraryFilterChips = ["全部", "已安装", "已禁用", "存在冲突", "外观", "武器", "语音"] as const;
