[package]
name = "hmm-app"
version = "0.1.0-alpha.0"
description = "Application use cases for Helsincy Mod Manager"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
hmm-core = { path = "../hmm-core" }
hmm-ports = { path = "../hmm-ports" }
serde_json.workspace = true
sha2 = "0.10.9"
thiserror.workspace = true
