[package]
name = "hmm-infra"
version = "0.1.0-alpha.0"
description = "Infrastructure adapters for Helsincy Mod Manager"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
fs2 = "0.4.3"
hmm-core = { path = "../hmm-core" }
hmm-ports = { path = "../hmm-ports" }
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "webp"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
tempfile = "3.27.0"
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.56"

[dev-dependencies]
